[package]
name = "holdem"
version = "0.0.1"
authors = ["Vladislav Supalov <v.supalov@google.com>"]

[lib]
name = "holdem"

[dependencies.cards]
git = "file:///home/toasty/Code/Rust/cards-rs"

#[dependencies]
#cards = "0.1.0"
