[package]
name = "holdem"
version = "0.1.0"
authors = ["Vladislav Supalov <v.supalov@google.com>"]

[lib]
name = "holdem"

[dependencies.cards]
git = "https://github.com/th4t/cards-rs.git"

#[dependencies]
#cards = "0.1.0"
