[package]
name = "holdem"
version = "0.1.0"
authors = ["Vladislav Supalov <v.supalov@gmail.com>"]
keywords = ["cards", "poker"]
description = "Texas Hold'em specific types and logic."
license = "MIT"
readme = "README.md"

[lib]
name = "holdem"

[dependencies]
cards = "1.1.0"
